### PR TITLE
remove widget functionality

### LINKED ISSUE #2208: Gallery Widget Broken
The widget for the Gallery app is broken.
When you go to widget > Gallery > Single photo
It will take you to the gallery app to select a photo. You click the photo, it offers to crop it, and then it will just flicker and not show up.

I am using Neo launcher if that matters.

### PR DESCRIPTION
**Pull request by empratyush**
closes [#2208 ](https://github.com/GrapheneOS/os-issue-tracker/issues/2208)

### CODE REVIEW

**Comment by muhomorr** [comment]
Only single-image mode of the Gallery widget broken, the other two (Album and Shuffle all) work fine.
It's still a nice widget, despite its age. 
I think it's better to just remove the single-image option, or to fix it, if it's a simple fix.

**Comment by empratyush** [comment]
okay.

**Comment by muhomorr** [comment]
Album and "Shuffle all" modes are broken after reboot too (widget becomes blank).
See if this issue can be fixed easily. If there's no simple fix, can merge this PR as is.

**Comment by empratyush** [comment]
@muhomorr  As per our discussion (on matrix), I have updated it to remove the whole widget functionality.

**Pull request merged**
